//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::MediaType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "genres")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tmdb_id: Option<i32>,
    pub name: String,
    pub r#type: MediaType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::media_genres::Entity")]
    MediaGenres,
}

impl Related<super::media_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaGenres.def()
    }
}

impl Related<super::media::Entity> for Entity {
    fn to() -> RelationDef {
        super::media_genres::Relation::Media.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::media_genres::Relation::Genres.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
