//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::ImageFileType;
use super::sea_orm_active_enums::ImageSource;
use super::sea_orm_active_enums::ImageType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "images")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub path: String,
    pub source: ImageSource,
    pub source_path: Option<String>,
    pub r#type: ImageType,
    pub file_type: ImageFileType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::image_sizes::Entity")]
    ImageSizes,
    #[sea_orm(has_one = "super::manual_image_references::Entity")]
    ManualImageReferences,
}

impl Related<super::image_sizes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageSizes.def()
    }
}

impl Related<super::manual_image_references::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ManualImageReferences.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
