//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod app_tokens;
pub mod genres;
pub mod image_sizes;
pub mod images;
pub mod languages;
pub mod logs;
pub mod manual_image_references;
pub mod media;
pub mod media_genres;
pub mod media_locks;
pub mod media_tags;
pub mod movie_locks;
pub mod movies;
pub mod sea_orm_active_enums;
pub mod seasons;
pub mod series;
pub mod series_locks;
pub mod sources;
pub mod tags;
pub mod titles;
pub mod users;
pub mod watchlist;
