//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod credits;
pub mod episodes;
pub mod genres;
pub mod images;
pub mod languages;
pub mod logs;
pub mod media;
pub mod media_genres;
pub mod media_tags;
pub mod movies;
pub mod people;
pub mod sea_orm_active_enums;
pub mod seasons;
pub mod series;
pub mod series_watchlist;
pub mod sources;
pub mod tags;
pub mod titles;
pub mod user_media;
pub mod users;
pub mod watchlist;
