//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "movie_locks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub movie_id: i32,
    pub release_date: bool,
    pub runtime: bool,
    pub status: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::movies::Entity",
        from = "Column::MovieId",
        to = "super::movies::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Movies,
}

impl Related<super::movies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Movies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
