//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::app_tokens::Entity as AppTokens;
pub use super::credits::Entity as Credits;
pub use super::episodes::Entity as Episodes;
pub use super::genres::Entity as Genres;
pub use super::images::Entity as Images;
pub use super::languages::Entity as Languages;
pub use super::logs::Entity as Logs;
pub use super::media::Entity as Media;
pub use super::media_genres::Entity as MediaGenres;
pub use super::media_tags::Entity as MediaTags;
pub use super::movies::Entity as Movies;
pub use super::people::Entity as People;
pub use super::seasons::Entity as Seasons;
pub use super::series::Entity as Series;
pub use super::sources::Entity as Sources;
pub use super::tags::Entity as Tags;
pub use super::titles::Entity as Titles;
pub use super::users::Entity as Users;
pub use super::watchlist::Entity as Watchlist;
