//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "credits_type")]
pub enum CreditsType {
    #[sea_orm(string_value = "cast")]
    Cast,
    #[sea_orm(string_value = "crew")]
    Crew,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "media_type")]
pub enum MediaType {
    #[sea_orm(string_value = "movie")]
    Movie,
    #[sea_orm(string_value = "series")]
    Series,
}
