//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "media_type")]
pub enum MediaType {
    #[sea_orm(string_value = "movie")]
    Movie,
    #[sea_orm(string_value = "series")]
    Series,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "source_type")]
pub enum SourceType {
    #[sea_orm(string_value = "torrent")]
    Torrent,
    #[sea_orm(string_value = "web")]
    Web,
    #[sea_orm(string_value = "jellyfin")]
    Jellyfin,
}
