//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub username: String,
    pub password_hash: String,
    pub admin: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_media::Entity")]
    UserMedia,
    #[sea_orm(has_many = "super::watchlist::Entity")]
    Watchlist,
}

impl Related<super::user_media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMedia.def()
    }
}

impl Related<super::watchlist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Watchlist.def()
    }
}

impl Related<super::media::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_media::Relation::Media.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_media::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
